steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gca-gke-2025/zoonotic-web:latest', '-f', 'web.Dockerfile', '.']
  id: 'Build Web Image'

images:
- 'gcr.io/gca-gke-2025/zoonotic-web'
