steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gca-gke-2025/training:latest', '-f', 'training.Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gca-gke-2025/training']
images:
- 'gcr.io/gca-gke-2025/training'
