steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gca-gke-2025/download-data', '-f', 'scripts/Dockerfile.download', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gca-gke-2025/download-data']
images:
- 'gcr.io/gca-gke-2025/download-data'
