steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gca-gke-2025/gcs-test', '-f', 'Dockerfile.gcs-test', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gca-gke-2025/gcs-test']
images:
- 'gcr.io/gca-gke-2025/gcs-test'
logsBucket: 'gs://zntic-data/logs'
options:
  logging: GCS_ONLY