apiVersion: batch/v1
kind: Job
metadata:
  name: download-data
spec:
  template:
    spec:
      serviceAccountName: zntic-gke-sa
      containers:
      - name: download-data
        image: gcr.io/gca-gke-2025/data-processing
        command: ["python", "download_data.py"]
      restartPolicy: Never
      imagePullSecrets:
      - name: gcr-secret
  backoffLimit: 4
