description: Auto-build training service when training files change
filename: cloudbuild/cloudbuild-training.yaml
github:
  name: zntic-train
  owner: fkcurrie
  push:
    branch: ^main$
includedFiles:
- training/**
- requirements.txt
name: training-auto-trigger
serviceAccount: projects/gca-gke-2025/serviceAccounts/764460891170-compute@developer.gserviceaccount.com