# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the script into the container
COPY scripts/download_data.py /app/

# Make the script executable
RUN chmod +x /app/download_data.py

# Run the script when the container launches
CMD ["python", "/app/download_data.py"]
